name: Create a comment on new issues and dump context


on:
  issues:
    types: [ opened ]

jobs:
  comment-with-action:
    runs-on: ubuntu-latest
    steps:
      - name: "dump github context"
        run: echo "{{ toJSON(github.event) }}" | jq
        shell: bash