name: Test, Build, Push and Deploy

on:
  push:
    branches:
      - master


env:
  LC_ALL: C.UTF-8
  LANG: C.UTF-8
  REGISTRY_DOMAIN: eu.gcr.io
  REGISTRY_URL: eu.gcr.io/mb-dotcom-prod

jobs:
  ################################################################################
  # Any inits, e.g: helps with env missing in with.<with_id> context
  ################################################################################

  main_init:
    name: Init
    runs-on: ubuntu-latest
    outputs:
      APP_NAME: ${{  steps.env_vars.outputs.APP_NAME  }}
      REGISTRY_DOMAIN: ${{  steps.env_vars.outputs.REGISTRY_DOMAIN  }}
      REGISTRY_URL: ${{  steps.env_vars.outputs.REGISTRY_URL  }}
      FULL_IMG_REF: ${{  steps.env_vars.outputs.FULL_IMG_REF  }}
      IMG_REF: ${{  steps.env_vars.outputs.IMG_REF  }}
    steps:
      - name: Init some vars
        id: env_vars
        run: |
          app_name="${{  vars.APP_NAME }}"
    
          echo "APP_NAME=$app_name" >> $GITHUB_OUTPUT
    
          reg_domain="${{  env.REGISTRY_DOMAIN  }}"
          echo "REGISTRY_DOMAIN=$reg_domain" >> $GITHUB_OUTPUT
    
          reg_url="${{  env.REGISTRY_URL  }}"
          echo "REGISTRY_URL=$reg_url" >> $GITHUB_OUTPUT
    
          echo "FULL_IMG_REF=$reg_url/$app_name:${{  vars.VERSION || github.sha  }}" >> $GITHUB_OUTPUT
    
          echo "IMG_REF=${{  vars.VERSION || github.sha  }}" >> $GITHUB_OUTPUT
    
